/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './src/routes/__root'
import { Route as SitemapDotxmlRouteImport } from './src/routes/sitemap[.]xml'
import { Route as RobotsDottxtRouteImport } from './src/routes/robots[.]txt'
import { Route as PortfolioRouteImport } from './src/routes/portfolio'
import { Route as ContactRouteImport } from './src/routes/contact'
import { Route as AboutRouteImport } from './src/routes/about'
import { Route as IndexRouteImport } from './src/routes/index'
import { Route as SodOrderingIndexRouteImport } from './src/routes/sod-ordering.index'
import { Route as ServiceAreasIndexRouteImport } from './src/routes/service-areas.index'
import { Route as ResourcesIndexRouteImport } from './src/routes/resources.index'
import { Route as OutdoorServicesIndexRouteImport } from './src/routes/outdoor-services.index'
import { Route as InteriorRenovationsIndexRouteImport } from './src/routes/interior-renovations.index'
import { Route as SodOrderingConfirmationRouteImport } from './src/routes/sod-ordering.confirmation'
import { Route as ServiceAreasCityRouteImport } from './src/routes/service-areas.$city'
import { Route as ResourcesSlugRouteImport } from './src/routes/resources.$slug'
import { Route as OutdoorServicesServiceRouteImport } from './src/routes/outdoor-services.$service'
import { Route as InteriorRenovationsServiceRouteImport } from './src/routes/interior-renovations.$service'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const PortfolioRoute = PortfolioRouteImport.update({
  id: '/portfolio',
  path: '/portfolio',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SodOrderingIndexRoute = SodOrderingIndexRouteImport.update({
  id: '/sod-ordering/',
  path: '/sod-ordering/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServiceAreasIndexRoute = ServiceAreasIndexRouteImport.update({
  id: '/service-areas/',
  path: '/service-areas/',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesIndexRoute = ResourcesIndexRouteImport.update({
  id: '/resources/',
  path: '/resources/',
  getParentRoute: () => rootRouteImport,
} as any)
const OutdoorServicesIndexRoute = OutdoorServicesIndexRouteImport.update({
  id: '/outdoor-services/',
  path: '/outdoor-services/',
  getParentRoute: () => rootRouteImport,
} as any)
const InteriorRenovationsIndexRoute =
  InteriorRenovationsIndexRouteImport.update({
    id: '/interior-renovations/',
    path: '/interior-renovations/',
    getParentRoute: () => rootRouteImport,
  } as any)
const SodOrderingConfirmationRoute = SodOrderingConfirmationRouteImport.update({
  id: '/sod-ordering/confirmation',
  path: '/sod-ordering/confirmation',
  getParentRoute: () => rootRouteImport,
} as any)
const ServiceAreasCityRoute = ServiceAreasCityRouteImport.update({
  id: '/service-areas/$city',
  path: '/service-areas/$city',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesSlugRoute = ResourcesSlugRouteImport.update({
  id: '/resources/$slug',
  path: '/resources/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const OutdoorServicesServiceRoute = OutdoorServicesServiceRouteImport.update({
  id: '/outdoor-services/$service',
  path: '/outdoor-services/$service',
  getParentRoute: () => rootRouteImport,
} as any)
const InteriorRenovationsServiceRoute =
  InteriorRenovationsServiceRouteImport.update({
    id: '/interior-renovations/$service',
    path: '/interior-renovations/$service',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/portfolio': typeof PortfolioRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/interior-renovations/$service': typeof InteriorRenovationsServiceRoute
  '/outdoor-services/$service': typeof OutdoorServicesServiceRoute
  '/resources/$slug': typeof ResourcesSlugRoute
  '/service-areas/$city': typeof ServiceAreasCityRoute
  '/sod-ordering/confirmation': typeof SodOrderingConfirmationRoute
  '/interior-renovations/': typeof InteriorRenovationsIndexRoute
  '/outdoor-services/': typeof OutdoorServicesIndexRoute
  '/resources/': typeof ResourcesIndexRoute
  '/service-areas/': typeof ServiceAreasIndexRoute
  '/sod-ordering/': typeof SodOrderingIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/portfolio': typeof PortfolioRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/interior-renovations/$service': typeof InteriorRenovationsServiceRoute
  '/outdoor-services/$service': typeof OutdoorServicesServiceRoute
  '/resources/$slug': typeof ResourcesSlugRoute
  '/service-areas/$city': typeof ServiceAreasCityRoute
  '/sod-ordering/confirmation': typeof SodOrderingConfirmationRoute
  '/interior-renovations': typeof InteriorRenovationsIndexRoute
  '/outdoor-services': typeof OutdoorServicesIndexRoute
  '/resources': typeof ResourcesIndexRoute
  '/service-areas': typeof ServiceAreasIndexRoute
  '/sod-ordering': typeof SodOrderingIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/portfolio': typeof PortfolioRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/interior-renovations/$service': typeof InteriorRenovationsServiceRoute
  '/outdoor-services/$service': typeof OutdoorServicesServiceRoute
  '/resources/$slug': typeof ResourcesSlugRoute
  '/service-areas/$city': typeof ServiceAreasCityRoute
  '/sod-ordering/confirmation': typeof SodOrderingConfirmationRoute
  '/interior-renovations/': typeof InteriorRenovationsIndexRoute
  '/outdoor-services/': typeof OutdoorServicesIndexRoute
  '/resources/': typeof ResourcesIndexRoute
  '/service-areas/': typeof ServiceAreasIndexRoute
  '/sod-ordering/': typeof SodOrderingIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contact'
    | '/portfolio'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/interior-renovations/$service'
    | '/outdoor-services/$service'
    | '/resources/$slug'
    | '/service-areas/$city'
    | '/sod-ordering/confirmation'
    | '/interior-renovations/'
    | '/outdoor-services/'
    | '/resources/'
    | '/service-areas/'
    | '/sod-ordering/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/portfolio'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/interior-renovations/$service'
    | '/outdoor-services/$service'
    | '/resources/$slug'
    | '/service-areas/$city'
    | '/sod-ordering/confirmation'
    | '/interior-renovations'
    | '/outdoor-services'
    | '/resources'
    | '/service-areas'
    | '/sod-ordering'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/contact'
    | '/portfolio'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/interior-renovations/$service'
    | '/outdoor-services/$service'
    | '/resources/$slug'
    | '/service-areas/$city'
    | '/sod-ordering/confirmation'
    | '/interior-renovations/'
    | '/outdoor-services/'
    | '/resources/'
    | '/service-areas/'
    | '/sod-ordering/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  PortfolioRoute: typeof PortfolioRoute
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  InteriorRenovationsServiceRoute: typeof InteriorRenovationsServiceRoute
  OutdoorServicesServiceRoute: typeof OutdoorServicesServiceRoute
  ResourcesSlugRoute: typeof ResourcesSlugRoute
  ServiceAreasCityRoute: typeof ServiceAreasCityRoute
  SodOrderingConfirmationRoute: typeof SodOrderingConfirmationRoute
  InteriorRenovationsIndexRoute: typeof InteriorRenovationsIndexRoute
  OutdoorServicesIndexRoute: typeof OutdoorServicesIndexRoute
  ResourcesIndexRoute: typeof ResourcesIndexRoute
  ServiceAreasIndexRoute: typeof ServiceAreasIndexRoute
  SodOrderingIndexRoute: typeof SodOrderingIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolio': {
      id: '/portfolio'
      path: '/portfolio'
      fullPath: '/portfolio'
      preLoaderRoute: typeof PortfolioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sod-ordering/': {
      id: '/sod-ordering/'
      path: '/sod-ordering'
      fullPath: '/sod-ordering/'
      preLoaderRoute: typeof SodOrderingIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/service-areas/': {
      id: '/service-areas/'
      path: '/service-areas'
      fullPath: '/service-areas/'
      preLoaderRoute: typeof ServiceAreasIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources/': {
      id: '/resources/'
      path: '/resources'
      fullPath: '/resources/'
      preLoaderRoute: typeof ResourcesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/outdoor-services/': {
      id: '/outdoor-services/'
      path: '/outdoor-services'
      fullPath: '/outdoor-services/'
      preLoaderRoute: typeof OutdoorServicesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/interior-renovations/': {
      id: '/interior-renovations/'
      path: '/interior-renovations'
      fullPath: '/interior-renovations/'
      preLoaderRoute: typeof InteriorRenovationsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sod-ordering/confirmation': {
      id: '/sod-ordering/confirmation'
      path: '/sod-ordering/confirmation'
      fullPath: '/sod-ordering/confirmation'
      preLoaderRoute: typeof SodOrderingConfirmationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/service-areas/$city': {
      id: '/service-areas/$city'
      path: '/service-areas/$city'
      fullPath: '/service-areas/$city'
      preLoaderRoute: typeof ServiceAreasCityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources/$slug': {
      id: '/resources/$slug'
      path: '/resources/$slug'
      fullPath: '/resources/$slug'
      preLoaderRoute: typeof ResourcesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/outdoor-services/$service': {
      id: '/outdoor-services/$service'
      path: '/outdoor-services/$service'
      fullPath: '/outdoor-services/$service'
      preLoaderRoute: typeof OutdoorServicesServiceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/interior-renovations/$service': {
      id: '/interior-renovations/$service'
      path: '/interior-renovations/$service'
      fullPath: '/interior-renovations/$service'
      preLoaderRoute: typeof InteriorRenovationsServiceRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  PortfolioRoute: PortfolioRoute,
  RobotsDottxtRoute: RobotsDottxtRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  InteriorRenovationsServiceRoute: InteriorRenovationsServiceRoute,
  OutdoorServicesServiceRoute: OutdoorServicesServiceRoute,
  ResourcesSlugRoute: ResourcesSlugRoute,
  ServiceAreasCityRoute: ServiceAreasCityRoute,
  SodOrderingConfirmationRoute: SodOrderingConfirmationRoute,
  InteriorRenovationsIndexRoute: InteriorRenovationsIndexRoute,
  OutdoorServicesIndexRoute: OutdoorServicesIndexRoute,
  ResourcesIndexRoute: ResourcesIndexRoute,
  ServiceAreasIndexRoute: ServiceAreasIndexRoute,
  SodOrderingIndexRoute: SodOrderingIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
