/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SodOrderingRouteImport } from './routes/sod-ordering'
import { Route as PortfolioRouteImport } from './routes/portfolio'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ServiceAreasIndexRouteImport } from './routes/service-areas.index'
import { Route as ResourcesIndexRouteImport } from './routes/resources.index'
import { Route as OutdoorServicesIndexRouteImport } from './routes/outdoor-services.index'
import { Route as InteriorRenovationsIndexRouteImport } from './routes/interior-renovations.index'
import { Route as ServiceAreasCityRouteImport } from './routes/service-areas.$city'
import { Route as ResourcesSlugRouteImport } from './routes/resources.$slug'
import { Route as OutdoorServicesServiceRouteImport } from './routes/outdoor-services.$service'
import { Route as InteriorRenovationsServiceRouteImport } from './routes/interior-renovations.$service'

const SodOrderingRoute = SodOrderingRouteImport.update({
  id: '/sod-ordering',
  path: '/sod-ordering',
  getParentRoute: () => rootRouteImport,
} as any)
const PortfolioRoute = PortfolioRouteImport.update({
  id: '/portfolio',
  path: '/portfolio',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServiceAreasIndexRoute = ServiceAreasIndexRouteImport.update({
  id: '/service-areas/',
  path: '/service-areas/',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesIndexRoute = ResourcesIndexRouteImport.update({
  id: '/resources/',
  path: '/resources/',
  getParentRoute: () => rootRouteImport,
} as any)
const OutdoorServicesIndexRoute = OutdoorServicesIndexRouteImport.update({
  id: '/outdoor-services/',
  path: '/outdoor-services/',
  getParentRoute: () => rootRouteImport,
} as any)
const InteriorRenovationsIndexRoute =
  InteriorRenovationsIndexRouteImport.update({
    id: '/interior-renovations/',
    path: '/interior-renovations/',
    getParentRoute: () => rootRouteImport,
  } as any)
const ServiceAreasCityRoute = ServiceAreasCityRouteImport.update({
  id: '/service-areas/$city',
  path: '/service-areas/$city',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesSlugRoute = ResourcesSlugRouteImport.update({
  id: '/resources/$slug',
  path: '/resources/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const OutdoorServicesServiceRoute = OutdoorServicesServiceRouteImport.update({
  id: '/outdoor-services/$service',
  path: '/outdoor-services/$service',
  getParentRoute: () => rootRouteImport,
} as any)
const InteriorRenovationsServiceRoute =
  InteriorRenovationsServiceRouteImport.update({
    id: '/interior-renovations/$service',
    path: '/interior-renovations/$service',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/portfolio': typeof PortfolioRoute
  '/sod-ordering': typeof SodOrderingRoute
  '/interior-renovations/$service': typeof InteriorRenovationsServiceRoute
  '/outdoor-services/$service': typeof OutdoorServicesServiceRoute
  '/resources/$slug': typeof ResourcesSlugRoute
  '/service-areas/$city': typeof ServiceAreasCityRoute
  '/interior-renovations/': typeof InteriorRenovationsIndexRoute
  '/outdoor-services/': typeof OutdoorServicesIndexRoute
  '/resources/': typeof ResourcesIndexRoute
  '/service-areas/': typeof ServiceAreasIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/portfolio': typeof PortfolioRoute
  '/sod-ordering': typeof SodOrderingRoute
  '/interior-renovations/$service': typeof InteriorRenovationsServiceRoute
  '/outdoor-services/$service': typeof OutdoorServicesServiceRoute
  '/resources/$slug': typeof ResourcesSlugRoute
  '/service-areas/$city': typeof ServiceAreasCityRoute
  '/interior-renovations': typeof InteriorRenovationsIndexRoute
  '/outdoor-services': typeof OutdoorServicesIndexRoute
  '/resources': typeof ResourcesIndexRoute
  '/service-areas': typeof ServiceAreasIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/portfolio': typeof PortfolioRoute
  '/sod-ordering': typeof SodOrderingRoute
  '/interior-renovations/$service': typeof InteriorRenovationsServiceRoute
  '/outdoor-services/$service': typeof OutdoorServicesServiceRoute
  '/resources/$slug': typeof ResourcesSlugRoute
  '/service-areas/$city': typeof ServiceAreasCityRoute
  '/interior-renovations/': typeof InteriorRenovationsIndexRoute
  '/outdoor-services/': typeof OutdoorServicesIndexRoute
  '/resources/': typeof ResourcesIndexRoute
  '/service-areas/': typeof ServiceAreasIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contact'
    | '/portfolio'
    | '/sod-ordering'
    | '/interior-renovations/$service'
    | '/outdoor-services/$service'
    | '/resources/$slug'
    | '/service-areas/$city'
    | '/interior-renovations/'
    | '/outdoor-services/'
    | '/resources/'
    | '/service-areas/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/portfolio'
    | '/sod-ordering'
    | '/interior-renovations/$service'
    | '/outdoor-services/$service'
    | '/resources/$slug'
    | '/service-areas/$city'
    | '/interior-renovations'
    | '/outdoor-services'
    | '/resources'
    | '/service-areas'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/contact'
    | '/portfolio'
    | '/sod-ordering'
    | '/interior-renovations/$service'
    | '/outdoor-services/$service'
    | '/resources/$slug'
    | '/service-areas/$city'
    | '/interior-renovations/'
    | '/outdoor-services/'
    | '/resources/'
    | '/service-areas/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  PortfolioRoute: typeof PortfolioRoute
  SodOrderingRoute: typeof SodOrderingRoute
  InteriorRenovationsServiceRoute: typeof InteriorRenovationsServiceRoute
  OutdoorServicesServiceRoute: typeof OutdoorServicesServiceRoute
  ResourcesSlugRoute: typeof ResourcesSlugRoute
  ServiceAreasCityRoute: typeof ServiceAreasCityRoute
  InteriorRenovationsIndexRoute: typeof InteriorRenovationsIndexRoute
  OutdoorServicesIndexRoute: typeof OutdoorServicesIndexRoute
  ResourcesIndexRoute: typeof ResourcesIndexRoute
  ServiceAreasIndexRoute: typeof ServiceAreasIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sod-ordering': {
      id: '/sod-ordering'
      path: '/sod-ordering'
      fullPath: '/sod-ordering'
      preLoaderRoute: typeof SodOrderingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolio': {
      id: '/portfolio'
      path: '/portfolio'
      fullPath: '/portfolio'
      preLoaderRoute: typeof PortfolioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/service-areas/': {
      id: '/service-areas/'
      path: '/service-areas'
      fullPath: '/service-areas/'
      preLoaderRoute: typeof ServiceAreasIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources/': {
      id: '/resources/'
      path: '/resources'
      fullPath: '/resources/'
      preLoaderRoute: typeof ResourcesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/outdoor-services/': {
      id: '/outdoor-services/'
      path: '/outdoor-services'
      fullPath: '/outdoor-services/'
      preLoaderRoute: typeof OutdoorServicesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/interior-renovations/': {
      id: '/interior-renovations/'
      path: '/interior-renovations'
      fullPath: '/interior-renovations/'
      preLoaderRoute: typeof InteriorRenovationsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/service-areas/$city': {
      id: '/service-areas/$city'
      path: '/service-areas/$city'
      fullPath: '/service-areas/$city'
      preLoaderRoute: typeof ServiceAreasCityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources/$slug': {
      id: '/resources/$slug'
      path: '/resources/$slug'
      fullPath: '/resources/$slug'
      preLoaderRoute: typeof ResourcesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/outdoor-services/$service': {
      id: '/outdoor-services/$service'
      path: '/outdoor-services/$service'
      fullPath: '/outdoor-services/$service'
      preLoaderRoute: typeof OutdoorServicesServiceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/interior-renovations/$service': {
      id: '/interior-renovations/$service'
      path: '/interior-renovations/$service'
      fullPath: '/interior-renovations/$service'
      preLoaderRoute: typeof InteriorRenovationsServiceRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  PortfolioRoute: PortfolioRoute,
  SodOrderingRoute: SodOrderingRoute,
  InteriorRenovationsServiceRoute: InteriorRenovationsServiceRoute,
  OutdoorServicesServiceRoute: OutdoorServicesServiceRoute,
  ResourcesSlugRoute: ResourcesSlugRoute,
  ServiceAreasCityRoute: ServiceAreasCityRoute,
  InteriorRenovationsIndexRoute: InteriorRenovationsIndexRoute,
  OutdoorServicesIndexRoute: OutdoorServicesIndexRoute,
  ResourcesIndexRoute: ResourcesIndexRoute,
  ServiceAreasIndexRoute: ServiceAreasIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from '../router.tsx'
import type { startInstance } from '../start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
